<?php

namespace App\Enums\Schedule;

use App\Traits\Enums\BackedEnumTrait;
use App\Traits\Enums\EnumTrait;

/**
 * Where/How the schedule was created
 */
enum ScheduleOrigin : string
{
    use EnumTrait, BackedEnumTrait;


    // Schedule was generated by the creation of a parent scheduleable
    case Generated = 'generated';

    // Schedule was created when a manual action was triggered, i.e., "Play now"
    case Manual    = 'manual';

    // Schedule was created from the schedule creation form
    case Scheduled = 'scheduled';

    // Schedule was created when a listing entry was created
    case Listing = 'listing';
}
